# Generated by Django 5.2.7 on 2025-10-27 00:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_category_book_checksum_book_license_info_and_more"),
        ("lessons", "0001_initial"),
        ("medialibrary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=20)),
                ("content", models.TextField()),
                (
                    "used_for",
                    models.CharField(
                        help_text="e.g. lesson_summary, question_generation",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="book",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="content",
        ),
        migrations.AddField(
            model_name="lesson",
            name="ai_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="prompt_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="reels_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="lesson",
            name="review_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="reviewed_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_type", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="artifacts/")),
                ("checksum", models.CharField(blank=True, max_length=128, null=True)),
                ("render_params", models.JSONField(blank=True, default=dict)),
                (
                    "generated_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="lessons.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_start", models.IntegerField(blank=True, null=True)),
                ("page_end", models.IntegerField(blank=True, null=True)),
                ("summary_notes", models.TextField(blank=True)),
                ("checksum", models.CharField(blank=True, max_length=128, null=True)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("license_info", models.TextField(blank=True, null=True)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="lessons.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Only"),
                            ("image", "Image Based"),
                            ("mixed", "Text + Image"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("question_text", models.TextField(blank=True, null=True)),
                ("answer_text", models.TextField(blank=True, null=True)),
                ("difficulty", models.CharField(blank=True, max_length=20, null=True)),
                ("topic", models.CharField(blank=True, max_length=100, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ai_model", models.CharField(blank=True, max_length=100, null=True)),
                ("ai_confidence", models.FloatField(default=0.0)),
                ("is_ai_generated", models.BooleanField(default=False)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answer_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answer_images",
                        to="medialibrary.medialibrary",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="lessons.lesson",
                    ),
                ),
                (
                    "question_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_images",
                        to="medialibrary.medialibrary",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lessons.lessonsource",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
