# Generated by Django 5.2.7 on 2025-10-27 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("lessons", "0002_prompttemplate_remove_lesson_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="courses.course",
            ),
            preserve_default=False,
        ),
    ]
