# Generated by Django 5.2.7 on 2025-10-29 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_bookexercise_block"),
        ("lessons", "0003_lesson_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonsource",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="books.bookblock",
            ),
        ),
        migrations.AddField(
            model_name="lessonsource",
            name="book_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="books.booklesson",
            ),
        ),
        migrations.AddField(
            model_name="lessonsource",
            name="part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="books.bookpart",
            ),
        ),
        migrations.CreateModel(
            name="LessonContentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField(default=0.0)),
                ("matched_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.bookblock",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_links",
                        to="lessons.lesson",
                    ),
                ),
            ],
        ),
    ]
