# Generated by Django 5.2.7 on 2025-11-03 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0016_rename_bookexercise_blockexercise_and_more"),
        ("flashcard", "0004_remove_card_flashcard_c_lesson__51d51a_idx_and_more"),
        ("lessons", "0004_lessonsource_block_lessonsource_book_lesson_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonquestion",
            name="answer_image",
        ),
        migrations.RemoveField(
            model_name="lessonquestion",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="lessonquestion",
            name="question_image",
        ),
        migrations.RemoveField(
            model_name="lessonquestion",
            name="source",
        ),
        migrations.RemoveField(
            model_name="lessonsource",
            name="block",
        ),
        migrations.RemoveField(
            model_name="lessonsource",
            name="book",
        ),
        migrations.RemoveField(
            model_name="lessonsource",
            name="book_lesson",
        ),
        migrations.RemoveField(
            model_name="lessonsource",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="lessonsource",
            name="part",
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("embedding_vector", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cards",
                    models.ManyToManyField(
                        related_name="cards_lesson", to="flashcard.card"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_block",
                        to="lessons.lesson",
                    ),
                ),
                (
                    "linked_blocks",
                    models.ManyToManyField(
                        related_name="course_linked_blocks", to="books.bookblock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "اختيار من متعدد"),
                            ("true_false", "صح أو خطأ"),
                            ("short_answer", "إجابة قصيرة"),
                            ("essay", "مقال"),
                        ],
                        default="mcq",
                        max_length=50,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                (
                    "correct_answer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("explanation", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_block_exercises",
                        to="lessons.block",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockLearningObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_block_objective",
                        to="lessons.block",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockReel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hook_text",
                    models.CharField(
                        help_text="جملة البداية التي تجذب الانتباه",
                        max_length=255,
                        verbose_name="نص الجذب (Hook)",
                    ),
                ),
                (
                    "body_summary",
                    models.TextField(
                        help_text="ما الذي يشرحه الريل في القسم الرئيسي؟",
                        verbose_name="ملخص الفكرة الرئيسية",
                    ),
                ),
                (
                    "outro_question",
                    models.CharField(
                        blank=True,
                        help_text="جملة بسيطة تشجع المشاهد على التفكير أو المتابعة",
                        max_length=255,
                        null=True,
                        verbose_name="سؤال ختامي",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("informative", "معلوماتي"),
                            ("enthusiastic", "متحمس"),
                            ("curious", "فضولي"),
                            ("motivational", "تحفيزي"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "visual_hint",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً: صور متحركة، أمثلة، أو عرض نصي بسيط",
                        max_length=255,
                        null=True,
                        verbose_name="اقتراح بصري",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "question_image",
                    models.ImageField(blank=True, null=True, upload_to="real_images/"),
                ),
                ("option1", models.CharField(blank=True, max_length=255, null=True)),
                ("option2", models.CharField(blank=True, max_length=255, null=True)),
                ("option3", models.CharField(blank=True, max_length=255, null=True)),
                ("option4", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "correct_option",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "A"), (2, "B"), (3, "C"), (4, "D")]
                    ),
                ),
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_block_reel",
                        to="lessons.block",
                    ),
                ),
            ],
            options={
                "verbose_name": "شكل الريل الخاص بالبلوك",
                "verbose_name_plural": "أشكال الريلز الخاصة بالبلوكات",
            },
        ),
        migrations.DeleteModel(
            name="LessonContentLink",
        ),
        migrations.DeleteModel(
            name="LessonQuestion",
        ),
        migrations.DeleteModel(
            name="LessonSource",
        ),
    ]
