# Generated by Django 5.2.7 on 2025-11-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_remove_lessonquestion_answer_image_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlockExercise",
            new_name="LessonBlockExercise",
        ),
    ]
