# Generated by Django 5.2.7 on 2025-11-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_rename_blockexercise_lessonblockexercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
