# Generated by Django 5.2.7 on 2025-11-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_block_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="block",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AddField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("text", "نص"),
                    ("image", "صورة"),
                    ("table", "جدول"),
                    ("example", "مثال توضيحي"),
                    ("note", "ملاحظة"),
                ],
                default="text",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="book_blocks/"),
        ),
    ]
