# Generated by Django 5.2.7 on 2025-11-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0008_alter_block_options_block_block_type_block_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocklearningobjective",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_block_objective",
                to="lessons.block",
            ),
        ),
        migrations.AlterField(
            model_name="blockreel",
            name="block",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_block_reel",
                to="lessons.block",
            ),
        ),
        migrations.AlterField(
            model_name="lessonblockexercise",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_block_exercises",
                to="lessons.block",
            ),
        ),
    ]
