# Generated by Django 5.2.7 on 2025-11-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_alter_blocklearningobjective_block_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockreel",
            options={},
        ),
    ]
