# Generated by Django 5.2.7 on 2025-11-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard", "0004_remove_card_flashcard_c_lesson__51d51a_idx_and_more"),
        ("lessons", "0010_alter_blockreel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="exercise",
            field=models.ManyToManyField(
                related_name="exercise_lesson", to="flashcard.card"
            ),
        ),
    ]
