# Generated by Django 5.2.7 on 2025-11-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0018_blockexercise_question_image_alter_book_pdf"),
        ("lessons", "0011_block_exercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="exercise",
            field=models.ManyToManyField(
                related_name="exercise_lesson", to="books.blockexercise"
            ),
        ),
        migrations.DeleteModel(
            name="LessonBlockExercise",
        ),
    ]
