# Generated by Django 5.2.7 on 2025-11-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0018_blockexercise_question_image_alter_book_pdf"),
        ("flashcard", "0004_remove_card_flashcard_c_lesson__51d51a_idx_and_more"),
        ("lessons", "0012_alter_block_exercise_delete_lessonblockexercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="cards",
            field=models.ManyToManyField(
                blank=True, related_name="cards_lesson", to="flashcard.card"
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="exercise",
            field=models.ManyToManyField(
                blank=True, related_name="exercise_lesson", to="books.blockexercise"
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="linked_blocks",
            field=models.ManyToManyField(
                blank=True, related_name="course_linked_blocks", to="books.bookblock"
            ),
        ),
    ]
