# Generated by Django 5.2.7 on 2025-10-27 00:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0002_prompttemplate_remove_lesson_book_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("front_text", models.TextField(blank=True, null=True)),
                (
                    "front_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Card_front_images/"
                    ),
                ),
                (
                    "front_video",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("question_text", models.TextField(blank=True, null=True)),
                (
                    "question_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Card_question_images/"
                    ),
                ),
                ("option_a", models.CharField(blank=True, max_length=255, null=True)),
                ("option_b", models.CharField(blank=True, max_length=255, null=True)),
                ("option_c", models.CharField(blank=True, max_length=255, null=True)),
                ("option_d", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Option A"),
                            ("B", "Option B"),
                            ("C", "Option C"),
                            ("D", "Option D"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "again_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "hard_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "good_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "easy_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_card",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="flashcard_c_created_14b81a_idx"
                    ),
                    models.Index(
                        fields=["lesson"], name="flashcard_c_lesson__51d51a_idx"
                    ),
                ],
            },
        ),
    ]
