# Generated by Django 5.2.7 on 2025-10-30 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_bookexercise_block"),
        ("flashcard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_block_card",
                to="books.bookblock",
            ),
        ),
    ]
