# Generated by Django 5.2.7 on 2025-10-31 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard", "0002_card_block"),
        ("lessons", "0004_lessonsource_block_lessonsource_book_lesson_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_card",
                to="lessons.lesson",
            ),
        ),
    ]
