# Generated by Django 5.2.7 on 2025-11-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard", "0003_alter_card_lesson"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="card",
            name="flashcard_c_lesson__51d51a_idx",
        ),
        migrations.RemoveField(
            model_name="card",
            name="lesson",
        ),
    ]
