# Generated by Django 5.2.7 on 2025-10-27 21:28

import django.core.validators
import django.db.models.deletion
import reels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0003_lesson_course"),
        ("medialibrary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReelTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Template Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "default_structure",
                    models.JSONField(
                        default=reels.models.get_default_structure,
                        help_text="Skeleton: lists of segment definitions for intro/body/outro",
                        verbose_name="Default Structure",
                    ),
                ),
                (
                    "ai_instructions",
                    models.JSONField(
                        default=reels.models.get_default_ai_instructions,
                        help_text="Prompts used by AI to generate text per part",
                        verbose_name="AI Instructions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "example_hook",
                    models.TextField(blank=True, verbose_name="Example Hook"),
                ),
            ],
            options={
                "verbose_name": "Reel Template",
                "verbose_name_plural": "Reel Templates",
            },
        ),
        migrations.CreateModel(
            name="Reel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Reel Title")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "audio_strategy",
                    models.CharField(
                        choices=[
                            ("global", "Global audio track"),
                            ("per_segment", "Audio per segment"),
                            ("none", "No audio"),
                        ],
                        default="global",
                        max_length=20,
                    ),
                ),
                (
                    "voice_type",
                    models.CharField(
                        default="ai", max_length=20, verbose_name="Voice Type"
                    ),
                ),
                (
                    "audio_track",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reels/audio_tracks/",
                        verbose_name="Global audio file",
                    ),
                ),
                ("ai_generated", models.BooleanField(default=False)),
                ("ai_generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "background_music",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_as_background",
                        to="medialibrary.medialibrary",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reels",
                        to="lessons.lesson",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reels.reeltemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reel",
                "verbose_name_plural": "Reels",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReelAILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("ai_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_logs",
                        to="reels.reel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReelSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part",
                    models.CharField(
                        choices=[
                            ("intro", "Intro"),
                            ("body", "Body"),
                            ("outro", "Outro"),
                        ],
                        default="body",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("talk", "Person speaking"),
                            ("text_overlay", "Text overlay"),
                            ("video_clip", "Video clip"),
                            ("image", "Image"),
                            ("music", "Music bed"),
                            ("pause", "Pause"),
                            ("animation", "Animation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Primary content (text or pointer)",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Display meta (position, font, transition, etc.)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=3)),
                (
                    "transition_in",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("fade", "Fade"),
                            ("slide", "Slide"),
                            ("zoom", "Zoom"),
                            ("cut", "Cut"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Transition from previous",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="reels/segments/audio/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="segment_media",
                        to="medialibrary.medialibrary",
                    ),
                ),
                (
                    "reel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="reels.reel",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_segments",
                        to="reels.reeltemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reel Segment",
                "verbose_name_plural": "Reel Segments",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReelBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("text", "Text"),
                            ("bullets", "Bullet Points"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("quote", "Quote"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="position, style, animation...",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="block_images",
                        to="medialibrary.medialibrary",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="block_videos",
                        to="medialibrary.medialibrary",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="reels.reelsegment",
                    ),
                ),
            ],
        ),
    ]
