# Generated by Django 5.2.7 on 2025-10-27 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="background_color",
            field=models.CharField(default="#FFFFFF", max_length=20),
        ),
        migrations.AddField(
            model_name="course",
            name="border_radius",
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name="course",
            name="checksum",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="desc_font",
            field=models.CharField(default="Tajawal", max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="license_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="main_font",
            field=models.CharField(default="Cairo", max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="padding",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="course",
            name="primary_color",
            field=models.CharField(default="#1E90FF", max_length=20),
        ),
        migrations.AddField(
            model_name="course",
            name="secondary_color",
            field=models.CharField(default="#FFD700", max_length=20),
        ),
        migrations.AddField(
            model_name="course",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="course",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="categories.grade",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="categories.program",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="categories.stage",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="categories.subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("stage", "grade", "program", "subject", "name")},
        ),
    ]
