# Generated by Django 5.2.7 on 2025-10-27 20:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_background_color_course_border_radius_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": [
                    "stage__name",
                    "grade__name",
                    "program__name",
                    "subject__name",
                    "name",
                ],
                "verbose_name": "الكورس",
                "verbose_name_plural": "الكورسات",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
