# Generated by Django 5.2.7 on 2025-10-25 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "file",
                    models.FileField(
                        upload_to="media_library/%Y/%m/%d/", verbose_name="File"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                        verbose_name="Media Type",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="File Size"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME Type"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="Usage Count"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Media Library",
                "verbose_name_plural": "Media Library",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["media_type"], name="slides_medi_media_t_403eb6_idx"
                    ),
                    models.Index(fields=["tags"], name="slides_medi_tags_bc6664_idx"),
                    models.Index(
                        fields=["created_at"], name="slides_medi_created_78d805_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slide_viewer",
                    models.ImageField(blank=True, null=True, upload_to="slides/bg/"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Slide Title",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "background_color",
                    models.CharField(
                        default="#FFFFFF",
                        max_length=20,
                        verbose_name="Background Color",
                    ),
                ),
                (
                    "background_opacity",
                    models.FloatField(default=1.0, verbose_name="Background Opacity"),
                ),
                (
                    "layout_style",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("title_content", "Title and Content"),
                            ("image_left", "Image Left"),
                            ("image_right", "Image Right"),
                            ("split_screen", "Split Screen"),
                            ("full_image", "Full Image"),
                        ],
                        default="default",
                        max_length=50,
                        verbose_name="Layout Style",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slide_backgrounds",
                        to="slides.medialibrary",
                        verbose_name="Background Image",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slide",
                "verbose_name_plural": "Slides",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("duplicate", "Duplicate"),
                            ("reorder", "Reorder"),
                            ("style_change", "Style Change"),
                            ("content_change", "Content Change"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Details"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_logs",
                        to="slides.slide",
                        verbose_name="Slide",
                    ),
                ),
            ],
            options={
                "verbose_name": "History Log",
                "verbose_name_plural": "History Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SlideBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("text", "Text"),
                            ("bullet_points", "Bullet Points"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("quote", "Quote"),
                            ("code", "Code"),
                            ("divider", "Divider"),
                            ("shape", "Shape"),
                        ],
                        max_length=20,
                        verbose_name="Block Type",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Content"),
                ),
                (
                    "position_x",
                    models.IntegerField(default=100, verbose_name="X Position"),
                ),
                (
                    "position_y",
                    models.IntegerField(default=100, verbose_name="Y Position"),
                ),
                ("width", models.IntegerField(default=200, verbose_name="Width")),
                ("height", models.IntegerField(default=100, verbose_name="Height")),
                ("z_index", models.IntegerField(default=1, verbose_name="Z-Index")),
                ("opacity", models.FloatField(default=1.0, verbose_name="Opacity")),
                (
                    "background_opacity",
                    models.FloatField(default=1.0, verbose_name="Background Opacity"),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="Arial, sans-serif",
                        max_length=100,
                        verbose_name="Font Family",
                    ),
                ),
                (
                    "font_size",
                    models.IntegerField(default=18, verbose_name="Font Size"),
                ),
                (
                    "font_color",
                    models.CharField(
                        default="#000000", max_length=20, verbose_name="Font Color"
                    ),
                ),
                (
                    "font_weight",
                    models.CharField(
                        default="normal", max_length=20, verbose_name="Font Weight"
                    ),
                ),
                (
                    "font_style",
                    models.CharField(
                        default="normal", max_length=20, verbose_name="Font Style"
                    ),
                ),
                (
                    "text_align",
                    models.CharField(
                        default="right", max_length=20, verbose_name="Text Align"
                    ),
                ),
                (
                    "text_decoration",
                    models.CharField(
                        default="none", max_length=20, verbose_name="Text Decoration"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Background Color",
                    ),
                ),
                (
                    "border_radius",
                    models.IntegerField(default=0, verbose_name="Border Radius"),
                ),
                (
                    "border_color",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Border Color",
                    ),
                ),
                (
                    "border_width",
                    models.IntegerField(default=0, verbose_name="Border Width"),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Extra Data"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slide_blocks",
                        to="slides.medialibrary",
                        verbose_name="Media",
                    ),
                ),
                (
                    "slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="slides.slide",
                        verbose_name="Slide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slide Block",
                "verbose_name_plural": "Slide Blocks",
                "ordering": ["z_index", "order", "created_at"],
            },
        ),
    ]
