# Generated by Django 5.2.7 on 2025-10-27 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medialibrary", "0001_initial"),
        ("slides", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideblock",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slide_blocks",
                to="medialibrary.medialibrary",
                verbose_name="Media",
            ),
        ),
        migrations.AlterField(
            model_name="slide",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slide_backgrounds",
                to="medialibrary.medialibrary",
                verbose_name="Background Image",
            ),
        ),
        migrations.AlterField(
            model_name="slide",
            name="slide_viewer",
            field=models.ImageField(blank=True, null=True, upload_to="slides/"),
        ),
        migrations.DeleteModel(
            name="MediaLibrary",
        ),
    ]
