# Generated by Django 5.2.7 on 2025-10-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0002_alter_slideblock_media_alter_slide_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideblock",
            name="layer_index",
            field=models.IntegerField(default=0, verbose_name="Layer Index"),
        ),
        migrations.AddField(
            model_name="slideblock",
            name="voice_script",
            field=models.TextField(
                blank=True,
                help_text="النص الذي سيتم تحويله إلى صوت عند عرض الشريحة.",
                null=True,
                verbose_name="Voice Script",
            ),
        ),
    ]
