# Generated by Django 5.2.7 on 2025-10-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0003_slideblock_layer_index_slideblock_voice_script"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideblock",
            name="speech_duration",
            field=models.FloatField(
                default=0, verbose_name="Speech Duration (seconds)"
            ),
        ),
    ]
