# Generated by Django 5.2.7 on 2025-11-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0004_slideblock_speech_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slideblock",
            name="opacity",
        ),
    ]
