# Generated by Django 5.2.7 on 2025-11-06 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medialibrary", "0001_initial"),
        ("slides", "0005_remove_slideblock_opacity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slideblock",
            name="layer_index",
        ),
        migrations.AddField(
            model_name="slideblock",
            name="opacity",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="background_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="background_opacity",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="border_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="border_radius",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="border_width",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="font_color",
            field=models.CharField(default="#000000", max_length=20),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="font_family",
            field=models.CharField(default="Arial, sans-serif", max_length=100),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="font_size",
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="font_style",
            field=models.CharField(default="normal", max_length=20),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="font_weight",
            field=models.CharField(default="normal", max_length=20),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="height",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slide_blocks",
                to="medialibrary.medialibrary",
            ),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="position_x",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="position_y",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="slide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="slides.slide",
            ),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="speech_duration",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="text_align",
            field=models.CharField(default="right", max_length=20),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="text_decoration",
            field=models.CharField(default="none", max_length=20),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="type",
            field=models.CharField(
                choices=[
                    ("title", "Title"),
                    ("text", "Text"),
                    ("bullet_points", "Bullet Points"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("quote", "Quote"),
                    ("code", "Code"),
                    ("divider", "Divider"),
                    ("shape", "Shape"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="voice_script",
            field=models.TextField(
                blank=True,
                help_text="النص الذي سيتم تحويله إلى صوت عند عرض الشريحة.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="width",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="z_index",
            field=models.IntegerField(default=1),
        ),
    ]
