# Generated by Django 5.2.7 on 2025-11-08 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0007_remove_slide_lesson_content_slide_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slide",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slides",
                to="slides.content",
            ),
        ),
    ]
