# Generated by Django 5.2.7 on 2025-11-16 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0009_alter_slide_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slide",
            name="content",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slides",
                to="slides.content",
            ),
        ),
    ]
