# Generated by Django 5.2.7 on 2025-10-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pdf", models.FileField(upload_to="books/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("primary_color", models.CharField(default="#1E90FF", max_length=20)),
                ("secondary_color", models.CharField(default="#FFD700", max_length=20)),
                (
                    "background_color",
                    models.CharField(default="#FFFFFF", max_length=20),
                ),
                ("main_font", models.CharField(default="Cairo", max_length=50)),
                ("desc_font", models.CharField(default="Tajawal", max_length=50)),
                ("border_radius", models.IntegerField(default=16)),
                ("padding", models.IntegerField(default=12)),
            ],
        ),
    ]
