# Generated by Django 5.2.7 on 2025-10-27 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(default="#2196F3", max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="checksum",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="license_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.category",
            ),
            preserve_default=False,
        ),
    ]
