# Generated by Django 5.2.7 on 2025-10-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_remove_book_category_book_subject_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="book",
            name="border_radius",
        ),
        migrations.RemoveField(
            model_name="book",
            name="checksum",
        ),
        migrations.RemoveField(
            model_name="book",
            name="desc_font",
        ),
        migrations.RemoveField(
            model_name="book",
            name="license_info",
        ),
        migrations.RemoveField(
            model_name="book",
            name="main_font",
        ),
        migrations.RemoveField(
            model_name="book",
            name="padding",
        ),
        migrations.RemoveField(
            model_name="book",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="book",
            name="secondary_color",
        ),
        migrations.RemoveField(
            model_name="book",
            name="version",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
