# Generated by Django 5.2.7 on 2025-10-28 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_remove_book_background_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("start_page", models.PositiveIntegerField()),
                ("end_page", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LearningObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BookBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="book_blocks/"),
                ),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "نص"),
                            ("image", "صورة"),
                            ("table", "جدول"),
                            ("example", "مثال توضيحي"),
                            ("note", "ملاحظة"),
                        ],
                        default="text",
                        max_length=50,
                    ),
                ),
                ("embedding_vector", models.JSONField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="books.booklesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("start_page", models.PositiveIntegerField(blank=True, null=True)),
                ("end_page", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="books.book",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booklesson",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="books.bookpart",
            ),
        ),
        migrations.CreateModel(
            name="BookExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "اختيار من متعدد"),
                            ("true_false", "صح أو خطأ"),
                            ("short_answer", "إجابة قصيرة"),
                            ("essay", "مقال"),
                        ],
                        default="mcq",
                        max_length=50,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                (
                    "correct_answer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("explanation", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="books.booklesson",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="books.bookpart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.bookblock",
                    ),
                ),
                (
                    "objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.learningobjective",
                    ),
                ),
            ],
        ),
    ]
