# Generated by Django 5.2.7 on 2025-10-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_booklesson_learningobjective_book_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookblock",
            name="title",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booklesson",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
