# Generated by Django 5.2.7 on 2025-10-29 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_bookblock_title_alter_booklesson_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookexercise",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="books.bookblock",
            ),
        ),
    ]
