# Generated by Django 5.2.7 on 2025-10-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_bookexercise_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockReelPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hook_text",
                    models.CharField(
                        help_text="جملة البداية التي تجذب الانتباه",
                        max_length=255,
                        verbose_name="نص الجذب (Hook)",
                    ),
                ),
                (
                    "body_summary",
                    models.TextField(
                        help_text="ما الذي يشرحه الريل في القسم الرئيسي؟",
                        verbose_name="ملخص الفكرة الرئيسية",
                    ),
                ),
                (
                    "outro_question",
                    models.CharField(
                        blank=True,
                        help_text="جملة بسيطة تشجع المشاهد على التفكير أو المتابعة",
                        max_length=255,
                        null=True,
                        verbose_name="سؤال ختامي",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("informative", "معلوماتي"),
                            ("enthusiastic", "متحمس"),
                            ("curious", "فضولي"),
                            ("motivational", "تحفيزي"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "visual_hint",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً: صور متحركة، أمثلة، أو عرض نصي بسيط",
                        max_length=255,
                        null=True,
                        verbose_name="اقتراح بصري",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "question_image",
                    models.ImageField(blank=True, null=True, upload_to="real_images/"),
                ),
                ("option1", models.CharField(blank=True, max_length=255, null=True)),
                ("option2", models.CharField(blank=True, max_length=255, null=True)),
                ("option3", models.CharField(blank=True, max_length=255, null=True)),
                ("option4", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "correct_option",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "A"), (2, "B"), (3, "C"), (4, "D")]
                    ),
                ),
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reel_preview",
                        to="books.bookblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "شكل الريل الخاص بالبلوك",
                "verbose_name_plural": "أشكال الريلز الخاصة بالبلوكات",
            },
        ),
    ]
