# Generated by Django 5.2.7 on 2025-10-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_blockreelpreview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blockreelpreview",
            old_name="question_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="blockreelpreview",
            old_name="question_text",
            new_name="question",
        ),
    ]
