# Generated by Django 5.2.7 on 2025-10-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_rename_question_image_blockreelpreview_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlockReelPreview",
        ),
    ]
