# Generated by Django 5.2.7 on 2025-10-31 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_blockreel"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookblock",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="bookblock",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name="BlockLearningObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objective_block",
                        to="books.bookblock",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BlockObjective",
        ),
        migrations.DeleteModel(
            name="LearningObjective",
        ),
    ]
