# Generated by Django 5.2.7 on 2025-10-31 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0012_bookblock_created_at_bookblock_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookblock",
            options={"ordering": ["order", "created_at"]},
        ),
    ]
