# Generated by Django 5.2.7 on 2025-11-01 02:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0013_alter_bookblock_options"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.grade",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.program",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.stage",
            ),
        ),
        migrations.AddField(
            model_name="booklesson",
            name="embedding_vector",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.subject",
            ),
        ),
        migrations.AlterField(
            model_name="bookblock",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="AIBookLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                ("embedding_vector", models.JSONField(blank=True, null=True)),
                (
                    "linked_lessons",
                    models.ManyToManyField(
                        related_name="linked_ai_lessons", to="books.booklesson"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("embedding_vector", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_blocks",
                    models.ManyToManyField(
                        related_name="linked_ai_blocks", to="books.bookblock"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_blocks",
                        to="books.aibooklesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("embedding_vector", models.JSONField(blank=True, null=True)),
                (
                    "ai_lesson",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lesson_index",
                        to="books.aibooklesson",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.grade",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.program",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.stage",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("title", "stage", "grade", "program", "subject")},
            },
        ),
    ]
