# Generated by Django 5.2.7 on 2025-11-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_book_grade_book_program_book_stage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookblock",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
