# Generated by Django 5.2.7 on 2025-11-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0015_alter_bookblock_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookExercise",
            new_name="BlockExercise",
        ),
        migrations.RemoveField(
            model_name="aibooklesson",
            name="linked_lessons",
        ),
        migrations.RemoveField(
            model_name="lessonindex",
            name="ai_lesson",
        ),
        migrations.AddField(
            model_name="lessonindex",
            name="lesson",
            field=models.ManyToManyField(
                related_name="book_lesson_index", to="books.booklesson"
            ),
        ),
        migrations.DeleteModel(
            name="AIBlock",
        ),
        migrations.DeleteModel(
            name="AIBookLesson",
        ),
    ]
