# Generated by Django 5.2.7 on 2025-11-03 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0016_rename_bookexercise_blockexercise_and_more"),
        ("lessons", "0007_block_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonindex",
            name="book_lesson",
            field=models.ManyToManyField(
                related_name="book_lesson_index", to="books.booklesson"
            ),
        ),
        migrations.RemoveField(
            model_name="lessonindex",
            name="lesson",
        ),
        migrations.AddField(
            model_name="lessonindex",
            name="lesson",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_lesson_index",
                to="lessons.lesson",
            ),
        ),
    ]
