# Generated by Django 5.2.7 on 2025-11-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0017_lessonindex_book_lesson_remove_lessonindex_lesson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockexercise",
            name="question_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="block_exercises/"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="books/"),
        ),
    ]
